title:              K's blog
email:              hwasun.kim2019@gmail.com
description:        Better late than never
author:             hskim
baseurl:            
url:                "https://hskim2019.github.io"

# Social Profiles
github_username:    hskim2019
linkedin_username:  whasun-kim-03278713a

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
